apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
  labels:
    app: kibana
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5601
    protocol: TCP
    targetPort: http
  selector:
    app: kibana
