apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        flush        1
        log_level    info
        parsers_file parsers.conf
        stream       stdout

    @INCLUDE input-kubernetes.conf

    @INCLUDE filter-kubernetes.conf

    @INCLUDE output-elasticsearch.conf

    @INCLUDE output-kubernetes.conf

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Kubernetes_URL      https://kubernetes.default.svc.cluster.local
        Kubernetes_CA_File  /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kubernetes_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
